// filament_db.h - the Filament Field Guide, as a flash-resident table.
//
// GENERATED by tools/gen_filament_db.py - do not edit by hand. Regenerate with
//   python3 tools/gen_filament_db.py [--src <clone of the guide>]
// and verify a committed copy with `--check` (exits non-zero when stale).
//
// Source:  https://pwsh.github.io/filament-field-guide/data/index.json
//          (+ data/filaments/<id>.json for each entry)
// Fetched: 2026-08-26
// Records: 90 filaments (guide index reports 90), 100 Bambu filament ids
//
// The filament data is (c) the Filament Field Guide contributors and is used
// under the Creative Commons Attribution 4.0 International licence
// (CC BY 4.0, https://creativecommons.org/licenses/by/4.0/). The UI carries the
// same credit next to every value it shows ("Data: Filament Field Guide, CC BY 4.0").
//
// Only the fields the fan controller needs are kept: the ambient/chamber band,
// the part-cooling recommendation, the ventilation demand and four flags. Strings
// are fixed-size so the whole table is one contiguous PROGMEM blob with no
// pointers to relocate and no parsing at runtime.
//
// Definitions are compiled into exactly one translation unit: the file that
// defines BLSF_FILAMENT_DB_DEFINE before including this header (filament.cpp on
// the device, the test binary on the host). Everyone else gets the declarations.

#ifndef BLSF_FILAMENT_DB_H
#define BLSF_FILAMENT_DB_H

#include <stdint.h>

#if defined(ARDUINO) || defined(ESP_PLATFORM)
#include <pgmspace.h>
#endif
#ifndef PROGMEM
#define PROGMEM
#endif

namespace blsf {

// Polymer family, straight from the guide's `polymer_class`.
enum FilamentClass : uint8_t {
    FCLASS_COMPOSITE_OTHER = 0,
    FCLASS_ELASTOMER = 1,
    FCLASS_HIGH_PERFORMANCE = 2,
    FCLASS_POLYAMIDE = 3,
    FCLASS_POLYCARBONATE = 4,
    FCLASS_POLYESTER_COPOLYESTER = 5,
    FCLASS_POLYLACTIDE = 6,
    FCLASS_POLYOLEFIN = 7,
    FCLASS_POLYVINYL = 8,
    FCLASS_STYRENIC = 9,
    FCLASS_SUPPORT_BREAKAWAY = 10,
    FCLASS_SUPPORT_SOLUBLE = 11,
};

// `emissions.ventilation`: how badly the fumes need to go outside.
enum FilamentVent : uint8_t { VENT_OPTIONAL = 0, VENT_RECOMMENDED = 1, VENT_REQUIRED = 2 };

// `emissions.voc_level` / `emissions.particulate_level`.
enum FilamentLevel : uint8_t { LEVEL_NONE = 0, LEVEL_LOW = 1, LEVEL_MODERATE = 2, LEVEL_HIGH = 3 };

// FilamentInfo::flags
static const uint8_t FIL_ENCLOSURE_RECOMMENDED = 0x01;
static const uint8_t FIL_HEATED_CHAMBER_REQUIRED = 0x02;
static const uint8_t FIL_ENCLOSURE_OPEN_FOR_COOLING = 0x04;
static const uint8_t FIL_HARDENED_NOZZLE = 0x08;

// Sentinels: the guide simply has no figure for some materials.
static const int8_t  FIL_TEMP_NA = -1;
static const uint8_t FIL_PARTCOOL_NA = 255;

struct FilamentInfo {
    char    id[24];         // guide id, e.g. "pla-cf" - also the URL fragment
    char    name[32];       // display name, e.g. "ABS"
    uint8_t polymerClass;   // FilamentClass
    int8_t  chamberMin;     // degC ambient band, FIL_TEMP_NA when the guide has none
    int8_t  chamberRec;
    int8_t  chamberMax;
    uint8_t partCoolRec;    // recommended part-cooling fan, %, FIL_PARTCOOL_NA if unknown
    uint8_t vent;           // FilamentVent
    uint8_t flags;          // FIL_* bits
    uint8_t voc;            // FilamentLevel
    uint8_t particulate;    // FilamentLevel
};

// A bare `tray_info_idx` ("GFB00") with no usable tray_type still has to
// resolve to a material, so the Bambu Studio id list travels with us.
struct BambuFilament {
    char idx[8];           // "GFA00" .. "GFSNL08"
    char type[12];          // Bambu filament_type, e.g. "PLA-CF"
};

static const uint16_t FILAMENT_DB_COUNT = 90;
static const uint16_t BAMBU_DB_COUNT = 100;

extern const FilamentInfo FILAMENT_DB[FILAMENT_DB_COUNT] PROGMEM;
extern const BambuFilament BAMBU_DB[BAMBU_DB_COUNT] PROGMEM;

// ESP32 flash is memory-mapped, so a PROGMEM record is read like any other
// const object. These accessors exist so filament_match.h never touches the
// arrays directly and stays compilable on the host.
inline const FilamentInfo* filamentDbAt(uint16_t i)
{
    return i < FILAMENT_DB_COUNT ? &FILAMENT_DB[i] : nullptr;
}
inline uint16_t filamentDbCount() { return FILAMENT_DB_COUNT; }
inline const BambuFilament* bambuDbAt(uint16_t i)
{
    return i < BAMBU_DB_COUNT ? &BAMBU_DB[i] : nullptr;
}
inline uint16_t bambuDbCount() { return BAMBU_DB_COUNT; }

inline const char* filamentClassName(uint8_t c)
{
    switch (c) {
        case FCLASS_COMPOSITE_OTHER: return "composite-other";
        case FCLASS_ELASTOMER: return "elastomer";
        case FCLASS_HIGH_PERFORMANCE: return "high-performance";
        case FCLASS_POLYAMIDE: return "polyamide";
        case FCLASS_POLYCARBONATE: return "polycarbonate";
        case FCLASS_POLYESTER_COPOLYESTER: return "polyester-copolyester";
        case FCLASS_POLYLACTIDE: return "polylactide";
        case FCLASS_POLYOLEFIN: return "polyolefin";
        case FCLASS_POLYVINYL: return "polyvinyl";
        case FCLASS_STYRENIC: return "styrenic";
        case FCLASS_SUPPORT_BREAKAWAY: return "support-breakaway";
        case FCLASS_SUPPORT_SOLUBLE: return "support-soluble";
        default: return "other";
    }
}

inline const char* filamentVentName(uint8_t v)
{
    return v == VENT_REQUIRED ? "required" : (v == VENT_RECOMMENDED ? "recommended" : "optional");
}

inline const char* filamentLevelName(uint8_t v)
{
    switch (v) {
        case LEVEL_LOW: return "low";
        case LEVEL_MODERATE: return "moderate";
        case LEVEL_HIGH: return "high";
        default: return "none";
    }
}

#ifdef BLSF_FILAMENT_DB_DEFINE

// { id, name, class, chamberMin/Rec/Max, partCool, vent, flags, voc, particulate }
const FilamentInfo FILAMENT_DB[FILAMENT_DB_COUNT] PROGMEM = {
    {"abs", "ABS", FCLASS_STYRENIC, 40, 50, 60, 0, 2, 0x01, 3, 3},
    {"abs-cf", "ABS-CF", FCLASS_COMPOSITE_OTHER, 40, 50, 60, 0, 2, 0x09, 3, 3},
    {"abs-esd", "ABS-ESD", FCLASS_COMPOSITE_OTHER, 40, 50, 60, 10, 2, 0x01, 3, 3},
    {"abs-fr", "ABS-FR", FCLASS_STYRENIC, 40, 50, 60, 0, 2, 0x01, 3, 3},
    {"abs-gf", "ABS-GF", FCLASS_COMPOSITE_OTHER, 40, 50, 60, 0, 2, 0x09, 3, 3},
    {"abs-plus", "ABS+", FCLASS_STYRENIC, 40, 50, 60, 0, 2, 0x01, 3, 3},
    {"asa", "ASA", FCLASS_STYRENIC, 40, 55, 60, 15, 2, 0x01, 3, 3},
    {"asa-cf", "ASA-CF", FCLASS_COMPOSITE_OTHER, 40, 55, 60, 10, 2, 0x09, 3, 3},
    {"asa-gf", "ASA-GF", FCLASS_COMPOSITE_OTHER, 40, 60, 80, 10, 2, 0x09, 3, 3},
    {"bvoh", "BVOH", FCLASS_SUPPORT_SOLUBLE, 15, 22, 30, 60, 0, 0x00, 1, 1},
    {"cleaning", "Cleaning / Purge Filament", FCLASS_COMPOSITE_OTHER, -1, -1, -1, 255, 1, 0x00, 2, 2},
    {"copa", "CoPA", FCLASS_POLYAMIDE, 30, 40, 50, 0, 1, 0x09, 2, 2},
    {"cope", "CoPE", FCLASS_POLYESTER_COPOLYESTER, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"cpe", "CPE", FCLASS_POLYESTER_COPOLYESTER, 20, 25, 40, 10, 1, 0x00, 1, 2},
    {"hips", "HIPS", FCLASS_SUPPORT_BREAKAWAY, 30, 45, 55, 0, 2, 0x01, 3, 3},
    {"lw-asa", "LW-ASA", FCLASS_STYRENIC, 30, 45, 55, 10, 2, 0x01, 3, 3},
    {"lw-pla", "LW-PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 1, 0x04, 2, 2},
    {"lw-tpu", "LW-TPU", FCLASS_ELASTOMER, 18, 22, 30, 0, 1, 0x04, 1, 2},
    {"mabs", "MABS", FCLASS_STYRENIC, -1, -1, -1, 255, 2, 0x01, 3, 3},
    {"pa", "PA", FCLASS_POLYAMIDE, 35, 45, 55, 10, 1, 0x01, 3, 2},
    {"pa-cf", "PA-CF", FCLASS_COMPOSITE_OTHER, 30, 45, 60, 0, 1, 0x09, 3, 2},
    {"pa12", "PA12", FCLASS_POLYAMIDE, 30, 40, 50, 5, 1, 0x01, 2, 2},
    {"pa12-cf", "PA12-CF", FCLASS_COMPOSITE_OTHER, 30, 45, 55, 0, 1, 0x09, 2, 2},
    {"pa6", "PA6", FCLASS_POLYAMIDE, 35, 45, 55, 0, 1, 0x01, 3, 2},
    {"pa6-cf", "PA6-CF", FCLASS_COMPOSITE_OTHER, 35, 45, 60, 0, 1, 0x09, 3, 2},
    {"pa6-gf", "PA6-GF", FCLASS_COMPOSITE_OTHER, 35, 45, 60, 0, 1, 0x09, 3, 2},
    {"pa612", "PA612", FCLASS_POLYAMIDE, 25, 40, 50, 0, 1, 0x09, 2, 2},
    {"pa66", "PA66", FCLASS_POLYAMIDE, 40, 50, 60, 0, 1, 0x01, 3, 2},
    {"pbat", "PBAT", FCLASS_POLYESTER_COPOLYESTER, 15, 22, 30, 50, 1, 0x04, 1, 1},
    {"pbt", "PBT", FCLASS_POLYESTER_COPOLYESTER, -1, -1, -1, 0, 1, 0x01, 1, 2},
    {"pc", "PC", FCLASS_POLYCARBONATE, 45, 55, 70, 5, 1, 0x01, 2, 2},
    {"pc-abs", "PC-ABS", FCLASS_POLYCARBONATE, 90, -1, 100, 5, 2, 0x01, 3, 3},
    {"pc-gf", "PC-GF", FCLASS_COMPOSITE_OTHER, 45, 55, 70, 5, 2, 0x09, 2, 3},
    {"pc-pbt", "PC-PBT", FCLASS_POLYCARBONATE, 100, 105, 110, 0, 1, 0x03, 2, 3},
    {"pctg", "PCTG", FCLASS_POLYESTER_COPOLYESTER, 20, 28, 40, 30, 1, 0x01, 2, 1},
    {"pctg-cf", "PCTG-CF", FCLASS_COMPOSITE_OTHER, 18, 28, 45, 10, 1, 0x08, 2, 2},
    {"pctg-gf", "PCTG-GF", FCLASS_COMPOSITE_OTHER, 18, 28, 45, 10, 1, 0x08, 2, 2},
    {"pe", "PE", FCLASS_POLYOLEFIN, -1, -1, -1, 25, 1, 0x09, 1, 1},
    {"peba", "PEBA", FCLASS_ELASTOMER, 18, 25, 35, 20, 1, 0x00, 1, 1},
    {"peek", "PEEK", FCLASS_HIGH_PERFORMANCE, 70, 120, 127, 0, 2, 0x03, 2, 3},
    {"pei-ultem", "PEI / ULTEM", FCLASS_HIGH_PERFORMANCE, 85, 90, 90, 0, 2, 0x03, 2, 3},
    {"pekk", "PEKK", FCLASS_HIGH_PERFORMANCE, 70, 110, 127, 0, 2, 0x03, 2, 3},
    {"pet", "PET", FCLASS_POLYESTER_COPOLYESTER, 25, 35, 45, 50, 1, 0x01, 2, 1},
    {"pet-cf", "PET-CF", FCLASS_COMPOSITE_OTHER, 45, 50, 60, 30, 1, 0x09, 2, 2},
    {"pet-gf", "PET-GF", FCLASS_COMPOSITE_OTHER, 25, 40, 50, 20, 1, 0x09, 2, 2},
    {"petg", "PETG", FCLASS_POLYESTER_COPOLYESTER, 18, 25, 35, 40, 1, 0x00, 1, 2},
    {"petg-cf", "PETG-CF", FCLASS_COMPOSITE_OTHER, 18, 28, 40, 20, 1, 0x08, 1, 2},
    {"petg-esd", "PETG-ESD", FCLASS_COMPOSITE_OTHER, 18, 25, 35, 40, 1, 0x08, 1, 2},
    {"petg-gf", "PETG-GF", FCLASS_COMPOSITE_OTHER, 18, 28, 40, 20, 1, 0x08, 1, 2},
    {"petg-plus", "PETG+", FCLASS_POLYESTER_COPOLYESTER, 18, 25, 35, 60, 1, 0x00, 1, 2},
    {"pha", "PHA", FCLASS_POLYLACTIDE, 15, 22, 30, 50, 0, 0x04, 1, 1},
    {"pla", "PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"pla-cast", "Castable PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"pla-cf", "PLA-CF", FCLASS_COMPOSITE_OTHER, 15, 30, 45, 100, 0, 0x0C, 1, 1},
    {"pla-gf", "PLA-GF", FCLASS_COMPOSITE_OTHER, 15, 22, 30, 100, 1, 0x0C, 1, 1},
    {"pla-glitter", "Glitter PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"pla-glow", "Glow-in-the-Dark PLA", FCLASS_COMPOSITE_OTHER, 25, 30, 45, 100, 0, 0x0C, 1, 1},
    {"pla-gradient", "Gradient PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"pla-hf", "High-Flow PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"pla-ht", "High-Temperature Annealable PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 1, 0x04, 1, 1},
    {"pla-matte", "Matte PLA", FCLASS_POLYLACTIDE, 25, 30, 45, 100, 0, 0x04, 1, 1},
    {"pla-metal", "Metal-Filled PLA", FCLASS_COMPOSITE_OTHER, 15, 25, 30, 100, 0, 0x0C, 1, 1},
    {"pla-plus", "PLA+", FCLASS_POLYLACTIDE, 15, 25, 45, 100, 0, 0x04, 1, 1},
    {"pla-silk", "Silk PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"pla-stone", "Stone-Filled PLA", FCLASS_POLYLACTIDE, 15, 22, 30, 100, 0, 0x0C, 1, 1},
    {"pla-wood", "Wood-Filled PLA", FCLASS_COMPOSITE_OTHER, 15, 22, 30, 100, 1, 0x0C, 1, 2},
    {"pmma", "PMMA", FCLASS_COMPOSITE_OTHER, -1, -1, -1, 15, 1, 0x01, 2, 2},
    {"pp", "PP", FCLASS_POLYOLEFIN, 45, 50, 70, 80, 1, 0x01, 1, 1},
    {"pp-cf", "PP-CF", FCLASS_COMPOSITE_OTHER, -1, -1, -1, 255, 1, 0x09, 1, 1},
    {"pp-gf", "PP-GF", FCLASS_COMPOSITE_OTHER, 30, 45, 60, 50, 1, 0x09, 1, 1},
    {"ppa", "PPA", FCLASS_POLYAMIDE, 50, 70, 127, 0, 2, 0x0B, 3, 3},
    {"ppa-cf", "PPA-CF", FCLASS_COMPOSITE_OTHER, 50, 60, 80, 0, 2, 0x09, 3, 3},
    {"pps", "PPS", FCLASS_HIGH_PERFORMANCE, 50, 80, 90, 0, 2, 0x01, 2, 3},
    {"pps-cf", "PPS-CF", FCLASS_HIGH_PERFORMANCE, 25, 60, 90, 0, 2, 0x09, 2, 3},
    {"ppsu", "PPSU", FCLASS_HIGH_PERFORMANCE, 65, 85, 90, 10, 2, 0x03, 2, 3},
    {"pva", "PVA", FCLASS_SUPPORT_SOLUBLE, 15, 22, 30, 100, 0, 0x04, 1, 1},
    {"pvb", "PVB", FCLASS_POLYVINYL, 15, 22, 30, 100, 1, 0x04, 1, 1},
    {"sbs", "SBS", FCLASS_ELASTOMER, -1, -1, -1, 35, 1, 0x00, 1, 1},
    {"support-breakaway", "Breakaway Support", FCLASS_SUPPORT_BREAKAWAY, 15, 25, 45, 255, 1, 0x00, 1, 1},
    {"tpe", "TPE", FCLASS_ELASTOMER, 18, 22, 30, 0, 1, 0x00, 1, 1},
    {"tpu", "TPU", FCLASS_ELASTOMER, 18, 22, 30, 30, 1, 0x04, 1, 1},
    {"tpu-60a", "TPU 60A", FCLASS_ELASTOMER, 18, 22, 30, 25, 1, 0x04, 1, 1},
    {"tpu-60d", "TPU 60D", FCLASS_ELASTOMER, 18, 22, 30, 40, 1, 0x04, 1, 2},
    {"tpu-68d", "TPU 68D", FCLASS_ELASTOMER, 18, 22, 30, 40, 1, 0x04, 1, 1},
    {"tpu-72d", "TPU 72D", FCLASS_ELASTOMER, 18, 25, 35, 30, 1, 0x00, 1, 1},
    {"tpu-85a", "TPU 85A", FCLASS_ELASTOMER, 18, 22, 30, 30, 1, 0x04, 1, 1},
    {"tpu-90a", "TPU 90A", FCLASS_ELASTOMER, 18, 22, 30, 30, 1, 0x04, 1, 1},
    {"tpu-95a", "TPU 95A", FCLASS_ELASTOMER, 18, 22, 30, 30, 1, 0x04, 1, 1},
    {"tpu-98a", "TPU 98A", FCLASS_ELASTOMER, 18, 22, 30, 70, 1, 0x04, 1, 1},
    {"tpu-gf", "TPU-GF", FCLASS_COMPOSITE_OTHER, 18, 22, 30, 35, 1, 0x0C, 1, 1},
};

const BambuFilament BAMBU_DB[BAMBU_DB_COUNT] PROGMEM = {
    {"GFA00", "PLA"},
    {"GFA01", "PLA"},
    {"GFA02", "PLA"},
    {"GFA05", "PLA"},
    {"GFA06", "PLA"},
    {"GFA07", "PLA"},
    {"GFA08", "PLA"},
    {"GFA09", "PLA"},
    {"GFA10", "PLA"},
    {"GFA11", "PLA-AERO"},
    {"GFA12", "PLA"},
    {"GFA13", "PLA"},
    {"GFA15", "PLA"},
    {"GFA16", "PLA"},
    {"GFA17", "PLA"},
    {"GFA18", "PLA"},
    {"GFA19", "PLA"},
    {"GFA50", "PLA-CF"},
    {"GFB00", "ABS"},
    {"GFB01", "ASA"},
    {"GFB02", "ASA-AERO"},
    {"GFB50", "ABS-GF"},
    {"GFB51", "ASA-CF"},
    {"GFB60", "ABS"},
    {"GFB61", "ASA"},
    {"GFB98", "ASA"},
    {"GFB99", "ABS"},
    {"GFC00", "PC"},
    {"GFC01", "PC"},
    {"GFC99", "PC"},
    {"GFG00", "PETG"},
    {"GFG01", "PETG"},
    {"GFG02", "PETG"},
    {"GFG03", "PETG"},
    {"GFG50", "PETG-CF"},
    {"GFG60", "PETG"},
    {"GFG96", "PETG"},
    {"GFG97", "PCTG"},
    {"GFG98", "PETG-CF"},
    {"GFG99", "PETG"},
    {"GFL00", "PLA"},
    {"GFL01", "PLA"},
    {"GFL03", "PLA"},
    {"GFL04", "PLA"},
    {"GFL05", "PLA"},
    {"GFL06", "PETG"},
    {"GFL50", "PA6-CF"},
    {"GFL51", "PA-GF"},
    {"GFL52", "PA-CF"},
    {"GFL53", "PA"},
    {"GFL54", "PET-CF"},
    {"GFL55", "PETG-CF"},
    {"GFL95", "PLA"},
    {"GFL96", "PLA"},
    {"GFL98", "PLA-CF"},
    {"GFL99", "PLA"},
    {"GFN03", "PA-CF"},
    {"GFN04", "PA-CF"},
    {"GFN05", "PA6-CF"},
    {"GFN06", "PPA-CF"},
    {"GFN08", "PA-GF"},
    {"GFN96", "PPA-GF"},
    {"GFN97", "PPA-CF"},
    {"GFN98", "PA-CF"},
    {"GFN99", "PA"},
    {"GFP95", "PP-GF"},
    {"GFP96", "PP-CF"},
    {"GFP97", "PP"},
    {"GFP98", "PE-CF"},
    {"GFP99", "PE"},
    {"GFR98", "PHA"},
    {"GFR99", "EVA"},
    {"GFS00", "PLA"},
    {"GFS01", "PA"},
    {"GFS02", "PLA"},
    {"GFS03", "PA"},
    {"GFS04", "PVA"},
    {"GFS05", "PLA"},
    {"GFS06", "ABS"},
    {"GFS97", "BVOH"},
    {"GFS98", "HIPS"},
    {"GFS99", "PVA"},
    {"GFSNL02", "PLA"},
    {"GFSNL03", "PLA"},
    {"GFSNL04", "PLA"},
    {"GFSNL05", "PLA"},
    {"GFSNL06", "PLA"},
    {"GFSNL07", "PLA"},
    {"GFSNL08", "PETG"},
    {"GFT01", "PET-CF"},
    {"GFT02", "PPS-CF"},
    {"GFT97", "PPS"},
    {"GFT98", "PPS-CF"},
    {"GFU00", "TPU"},
    {"GFU01", "TPU"},
    {"GFU02", "TPU-AMS"},
    {"GFU03", "TPU"},
    {"GFU04", "TPU"},
    {"GFU98", "TPU-AMS"},
    {"GFU99", "TPU"},
};

#endif  // BLSF_FILAMENT_DB_DEFINE

}  // namespace blsf

#endif  // BLSF_FILAMENT_DB_H
